-- Главный конфиг — только подключает остальные файлы.
-- Всё, что нужно менять, лежит в ~/.config/hypr/config/*.lua

hl.config({ autogenerated = false })

require("config.monitors")
require("config.environment")
require("config.appearance")
require("config.layouts")
require("config.input")

-- k4 грузится ДО keybinds.lua специально: при конфликте побеждает то,
-- что объявлено позже, а мы хотим, чтобы твои бинды имели приоритет
-- над сгенерированными k4, если ты сам явно что-то переопределяешь ниже.
require("config.k4-autostart")
require("config.wallpaper-autostart")

require("config.keybinds")
require("config.windowrules")
